# Generated by Django 5.1.4 on 2024-12-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membername', models.CharField(max_length=100)),
                ('membercpm', models.CharField(max_length=100)),
                ('invetsmentamount', models.CharField(max_length=100)),
                ('investmentdate', models.CharField(max_length=100)),
            ],
        ),
    ]
