# Generated by Django 5.1.4 on 2024-12-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group10Hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='investmentdate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='invetsmentamount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
